language: python

python:
- 3.5

sudo: false

install:
- pip install requests

script:
- grep -P -o "((http|ftp|https)://)(([a-zA-Z0-9\._-]+\.[a-zA-Z]{2,6})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,4})*(/[a-zA-Z0-9\&%_\./-~-]*)?" README.md  > sites.txt
- python3 webtest.py